apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
spec:
  rules:
    - host: app1.tonysm.com
      http:
        paths:
          - backend:
              serviceName: app1
              servicePort: 80
    - host: app2.tonysm.com
      http:
        paths:
          - backend:
              serviceName: app2
              servicePort: 80