apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: app3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  selector:
    matchLabels:
      app: app3
  replicas: 1
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: hashicorp/http-echo
          args:
            - "-text=HelloFromApp3"
          ports:
            - containerPort: 5678
